/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

class UTMTest {
    @Test void nothing() {
        System.out.println("nothing");
    }
}
